baseurl: ""
url: "https://savithakandugula.github.io"

title: "Savitha Kandugula Portfolio"
author:
  name: "Savitha Kandugula"
  email: "savithakandugula4@gmail.com"

sass:
  sass_dir: assets
include:
  - assets
