theme: "minima"
baseurl: ""
url: "https://savithakandugula.github.io"

title: "Savitha Kandugula Portfolio"
author:
  name: "Savitha Kandugula"
  email: "savithakandugula4@gmail.com"

sass:
  sass_dir: assets

# Navigation pages (order matters)
header_pages:
  - index.md
  - about.md
  - resume.md
  - contact.md

minima:
  skin: "classic"

include:
  - assets/css/custom.css