title: "Savitha Kandugula Portfolio"
description: "A professional portfolio showcasing Business Analysis projects, case studies, and process improvements."
remote_theme: "remote_theme: daattali/beautiful-jekyll@6.0.1"
baseurl: ""
url: "https://savithakandugula.github.io"

author:
  name: "Savitha Kandugula"
  email: "savithakandugula4@gmail.com"

# Navigation pages (order matters)
header_pages:
  - index.md
  - about.md
  - resume.md
  - contact.md

